[package]
name = "rust-github-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0", features = ["full"] }
serde_json = "1.0.140"
vercel_runtime = "1.1.4"

[[bin]]
name = "rust-github-bot"
path = "api/bot.rs"
